/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed': '#301400',
        tertiary: '#7d3d00',
        'on-background': '#191c1d',
        'secondary-fixed': '#e5e2e1',
        'on-primary-fixed': '#25005a',
        'on-surface': '#191c1d',
        outline: '#7b7487',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#5a00c6',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#1c1b1b',
        'tertiary-container': '#a15100',
        'surface-tint': '#732ee4',
        'on-tertiary-fixed-variant': '#713700',
        'secondary-fixed-dim': '#c8c6c5',
        'surface-container-highest': '#e1e3e4',
        'surface-container-high': '#e7e8e9',
        'surface-dim': '#d9dadb',
        'surface-bright': '#f8f9fa',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-secondary-container': '#636262',
        'inverse-surface': '#2e3132',
        'primary-fixed-dim': '#d2bbff',
        'tertiary-fixed': '#ffdcc6',
        secondary: '#5f5e5e',
        'tertiary-fixed-dim': '#ffb784',
        'outline-variant': '#ccc3d8',
        'on-secondary-fixed-variant': '#474746',
        primary: '#630ed4',
        'on-primary-container': '#ede0ff',
        'on-tertiary-container': '#ffe0cd',
        'on-secondary': '#ffffff',
        'surface-variant': '#e1e3e4',
        'on-surface-variant': '#4a4455',
        'inverse-primary': '#d2bbff',
        'inverse-on-surface': '#f0f1f2',
        'surface-container': '#edeeef',
        'on-tertiary': '#ffffff',
        surface: '#f8f9fa',
        'primary-container': '#7c3aed',
        'secondary-container': '#e2dfde',
        background: '#f8f9fa',
        'surface-container-low': '#f3f4f5',
        'primary-fixed': '#eaddff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-x': '24px',
        gutter: '32px',
        'section-gap': '160px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'container-max': '1200px',
        'stack-lg': '32px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      fontFamily: {
        'headline-md': ['Geist', 'system-ui', 'sans-serif'],
        'headline-xl': ['Geist', 'system-ui', 'sans-serif'],
        'headline-xl-mobile': ['Geist', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
        'label-caps': ['Geist', 'system-ui', 'sans-serif'],
        'headline-lg': ['Geist', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'system-ui', 'sans-serif'],
        code: ['Geist', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-xl': ['64px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-xl-mobile': ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.3', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.8', fontWeight: '400' }],
        code: ['14px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      transitionDuration: {
        400: '400ms',
      },
      transitionTimingFunction: {
        // curva "soft" usada por el indicador del nav y los tilts
        soft: 'cubic-bezier(0.22, 1, 0.36, 1)',
        springy: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      keyframes: {
        'sheen-sweep': {
          '0%': { transform: 'translateX(-120%) skewX(-20deg)' },
          '100%': { transform: 'translateX(220%) skewX(-20deg)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
      },
      animation: {
        'sheen-sweep': 'sheen-sweep 0.9s ease-out',
        float: 'float 5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
